/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    invoices: Invoice;
    customers: Customer;
    accounts: Account;
    media: Media;
    notes: Note;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'bn-BD';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  photoUrl?: string | null;
  companyName?: string | null;
  companyNameArabic?: string | null;
  /**
   * 15-digit VAT registration number (e.g., 300000000000003)
   */
  vatNumber?: string | null;
  /**
   * Commercial Registration (CR) number issued by Ministry of Commerce (ZATCA Phase 2 requirement)
   */
  registrationNumber?: string | null;
  /**
   * ZATCA Phase 1 Requirement (Article 53): Complete address must be included on all invoices
   */
  address?: {
    /**
     * Building number (4 digits, e.g., 1234)
     */
    buildingNumber?: string | null;
    /**
     * Street name in English
     */
    streetName?: string | null;
    /**
     * Street name in Arabic
     */
    streetNameArabic?: string | null;
    /**
     * District/Neighborhood name
     */
    district?: string | null;
    /**
     * District/Neighborhood name in Arabic
     */
    districtArabic?: string | null;
    /**
     * City name
     */
    city?: string | null;
    /**
     * City name in Arabic
     */
    cityArabic?: string | null;
    /**
     * 5-digit postal code (e.g., 12345)
     */
    postalCode?: string | null;
    /**
     * Country name (default: Saudi Arabia)
     */
    country?: string | null;
    /**
     * Country name in Arabic (default: Saudi Arabia)
     */
    countryArabic?: string | null;
  };
  phone?: string | null;
  companyLogo?: (string | null) | Media;
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: string;
  invoiceNumber: string;
  /**
   * Invoice status - ZATCA requires invoices cannot be deleted, only voided/cancelled
   */
  status: 'active' | 'void' | 'cancelled';
  /**
   * ZATCA Phase 1 Requirement (Article 53, VAT Implementing Regulations): Standard for VAT-registered customers (B2B/B2G), Simplified for non-registered customers (B2C)
   */
  invoiceType: 'standard' | 'simplified';
  customer: string | Customer;
  date: string;
  dueDate: string;
  rowEntries: {
    description: string;
    account: string;
    quantity: number;
    price: number;
    taxRate: number;
    id?: string | null;
  }[];
  pricesExcludeTax?: boolean | null;
  discountTotal?: number | null;
  /**
   * QR code data URL (base64 image) - ZATCA Phase 1: Mandatory for Simplified invoices, optional for Standard invoices
   */
  qrCodeData: string;
  subtotal?: number | null;
  totalTax?: number | null;
  total?: number | null;
  createdBy: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name: string;
  /**
   * VAT registration number (if applicable)
   */
  vatNumber?: string | null;
  country?:
    | (
        | 'SA'
        | 'AE'
        | 'KW'
        | 'QA'
        | 'BH'
        | 'OM'
        | 'JO'
        | 'LB'
        | 'IQ'
        | 'SY'
        | 'YE'
        | 'PS'
        | 'EG'
        | 'SD'
        | 'LY'
        | 'TN'
        | 'DZ'
        | 'MA'
        | 'MR'
        | 'SO'
        | 'DJ'
        | 'KM'
      )
    | null;
  /**
   * Customer's VAT registration status in Saudi Arabia
   */
  vatTreatment: 'not_registered' | 'registered';
  /**
   * ZATCA Phase 1 Requirement (Article 53): Address required for B2B invoices (Standard Tax Invoices)
   */
  address?: {
    /**
     * Building number (4 digits, e.g., 1234)
     */
    buildingNumber?: string | null;
    /**
     * Street name in Arabic or English
     */
    streetName?: string | null;
    /**
     * District/Neighborhood name
     */
    district?: string | null;
    /**
     * City name
     */
    city?: string | null;
    /**
     * 5-digit postal code (e.g., 12345)
     */
    postalCode?: string | null;
    /**
     * Additional number (4 digits, optional)
     */
    additionalNumber?: string | null;
  };
  createdBy: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  name: string;
  createdBy: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: string;
  noteNumber: string;
  /**
   * ZATCA Phase 1 Requirement: Credit Note for returns/refunds, Debit Note for additional charges
   */
  documentType: 'credit' | 'debit';
  /**
   * The original invoice this note is associated with
   */
  originalInvoice: string | Invoice;
  /**
   * Note status - ZATCA requires notes cannot be deleted, only voided/cancelled
   */
  status: 'active' | 'void' | 'cancelled';
  customer: string | Customer;
  date: string;
  dueDate: string;
  /**
   * Reason for issuing this credit/debit note (e.g., 'Return of goods', 'Additional charges')
   */
  reason: string;
  rowEntries: {
    description: string;
    account: string;
    quantity: number;
    price: number;
    taxRate: number;
    id?: string | null;
  }[];
  pricesExcludeTax?: boolean | null;
  discountTotal?: number | null;
  /**
   * QR code data URL (base64 image) - ZATCA Phase 1: Mandatory for notes associated with Simplified invoices, optional for Standard invoices
   */
  qrCodeData?: string | null;
  subtotal?: number | null;
  totalTax?: number | null;
  total?: number | null;
  createdBy: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'invoices';
        value: string | Invoice;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'notes';
        value: string | Note;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  photoUrl?: T;
  companyName?: T;
  companyNameArabic?: T;
  vatNumber?: T;
  registrationNumber?: T;
  address?:
    | T
    | {
        buildingNumber?: T;
        streetName?: T;
        streetNameArabic?: T;
        district?: T;
        districtArabic?: T;
        city?: T;
        cityArabic?: T;
        postalCode?: T;
        country?: T;
        countryArabic?: T;
      };
  phone?: T;
  companyLogo?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  status?: T;
  invoiceType?: T;
  customer?: T;
  date?: T;
  dueDate?: T;
  rowEntries?:
    | T
    | {
        description?: T;
        account?: T;
        quantity?: T;
        price?: T;
        taxRate?: T;
        id?: T;
      };
  pricesExcludeTax?: T;
  discountTotal?: T;
  qrCodeData?: T;
  subtotal?: T;
  totalTax?: T;
  total?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  vatNumber?: T;
  country?: T;
  vatTreatment?: T;
  address?:
    | T
    | {
        buildingNumber?: T;
        streetName?: T;
        district?: T;
        city?: T;
        postalCode?: T;
        additionalNumber?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  name?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  noteNumber?: T;
  documentType?: T;
  originalInvoice?: T;
  status?: T;
  customer?: T;
  date?: T;
  dueDate?: T;
  reason?: T;
  rowEntries?:
    | T
    | {
        description?: T;
        account?: T;
        quantity?: T;
        price?: T;
        taxRate?: T;
        id?: T;
      };
  pricesExcludeTax?: T;
  discountTotal?: T;
  qrCodeData?: T;
  subtotal?: T;
  totalTax?: T;
  total?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}