"use client";

import { useFieldArray, useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Form, FormField, FormItem, FormLabel } from "@/components/ui/form";
import { EllipsisVertical, LucideTrash2, Plus } from "lucide-react";
import { Combobox } from "../ui/combo-box";
import { Label } from "../ui/label";
import Image from "next/image";
import { useState, useEffect} from "react";
import { useRouter } from "next/navigation";
import { CustomerCreateModal } from "../modal/CustomerCreateModal";
import { AccountCreateModal } from "../modal/AccountCreateModal";
import { getCustomers, getAccounts } from "@/lib/server-functions";
import { generateInvoiceQRCode } from "@/lib/qr-code-generator";
import QRCode from "qrcode";
import { UserData } from "../container/container";

interface RowEntry {
  description: string;
  account: string;
  quantity: number;
  price: number;
  taxRate: number;
}

interface InvoiceData {
  customer: string;
  invoiceNumber: string;
  date: string;
  dueDate: string;
  invoiceType: "standard" | "simplified";
  rowEntries: RowEntry[];
  pricesExcludeTax: boolean;
  discountTotal: number;
}

interface Customer {
  id: string;
  name: string;
  vatTreatment?: string;
}

interface Account {
  id: string;
  name: string;
}


export function Invoice({ user }: { user: UserData }) {
  const router = useRouter();
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [openCustomerModal, setOpenCustomerModal] = useState(false);
  const [openAccountModal, setOpenAccountModal] = useState(false);
  const [qrCodeDataURL, setQrCodeDataURL] = useState<string | null>(null);
  const form = useForm<InvoiceData>({
    defaultValues: {
      customer: "",
      invoiceNumber: "", // Will be auto-generated by backend
      date: new Date().toISOString().split("T")[0],
      dueDate: new Date().toISOString().split("T")[0],
      invoiceType: "simplified", // Default to simplified (B2C)
      rowEntries: [
        { description: "", account: "", quantity: 1, price: 0, taxRate: "" as any },
      ],
      pricesExcludeTax: true,
      discountTotal: 0,
    },
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "rowEntries",
  });

  const rowEntries = form.watch("rowEntries");
  const discountTotal = form.watch("discountTotal");
  const invoiceDate = form.watch("date");
  const customer = form.watch("customer");
  const invoiceType = form.watch("invoiceType");

  // Fetch customers function
  const fetchCustomers = async () => {
    setIsLoading(true);
    try {
      const result = await getCustomers();
      if (result.success && result.docs) {
        setCustomers(
          result.docs.map((customer: any) => ({
            id: customer.id,
            name: customer.name,
          }))
        );
      } else {
        console.error("Error fetching customers:", result.error);
      }
    } catch (error) {
      console.error("Error fetching customers:", error);
    } finally {
      setIsLoading(false);
    }
  };

  // Fetch accounts function
  const fetchAccounts = async () => {
    try {
      const result = await getAccounts();
      if (result.success && result.docs) {
        setAccounts(
          result.docs.map((account: any) => ({
            id: account.id,
            name: account.name,
          }))
        );
      } else {
        console.error("Error fetching accounts:", result.error);
      }
    } catch (error) {
      console.error("Error fetching accounts:", error);
    }
  };

  // Fetch customers and accounts on component mount
  useEffect(() => {
    fetchCustomers();
    fetchAccounts();
  }, []);

  const pricesExcludeTax = form.watch("pricesExcludeTax");

  const calculateLineTotal = (item: RowEntry) => {
    const baseAmount = item.quantity * item.price;
    // If prices exclude tax, add VAT to get total
    if (pricesExcludeTax) {
      return baseAmount + (baseAmount * item.taxRate) / 100;
    }
    // If prices include tax, the price already includes VAT
    return baseAmount;
  };

  const calculateSubtotal = () => {
    return rowEntries.reduce((sum, item) => {
      const baseAmount = item.quantity * item.price;
      if (pricesExcludeTax) {
        // Subtotal is base amount (excl. VAT)
        return sum + baseAmount;
      } else {
        // Subtotal is base amount minus VAT (extract base from price that includes VAT)
        const baseWithoutVAT = baseAmount / (1 + item.taxRate / 100);
        return sum + baseWithoutVAT;
      }
    }, 0);
  };

  const calculateTax = () => {
    return rowEntries.reduce((sum, item) => {
      const baseAmount = item.quantity * item.price;
      if (pricesExcludeTax) {
        // VAT calculated on base amount
        return sum + (baseAmount * item.taxRate) / 100;
      } else {
        // VAT extracted from price that includes VAT
        const vatAmount = baseAmount - baseAmount / (1 + item.taxRate / 100);
        return sum + vatAmount;
      }
    }, 0);
  };

  const subtotal = calculateSubtotal();
  const tax = calculateTax();
  const total = subtotal + tax - discountTotal;


  // Manual QR code generation
  const handleGenerateQRCode = async () => {
    // Validate required fields
    const missingFields: string[] = [];

    if (!user.companyName) missingFields.push("Company Name");
    if (!user.vatNumber) missingFields.push("Tax Registration Number");
    if (!customer) missingFields.push("Customer");
    if (!invoiceDate) missingFields.push("Invoice Date");
    if (total <= 0) missingFields.push("Invoice Total (must be greater than 0)");

    if (missingFields.length > 0) {
      alert(
        `Cannot generate QR code. The following required fields are missing:\n\n` +
          missingFields.map((field) => `• ${field}`).join("\n") +
          `\n\nPlease fill in all required fields.` +
          (missingFields.includes("Company Name") ||
          missingFields.includes("Tax Registration Number")
            ? `\n\nClick on "Company details" to add company information.`
            : "")
      );
      return;
    }

    try {
      const qrData = generateInvoiceQRCode({
        companyName: user.companyName!,
        vatNumber: user.vatNumber!,
        invoiceDate: new Date(invoiceDate),
        totalWithVAT: total,
        vatAmount: tax,
      });

      // Generate QR code image from the base64 data
      const qrCodeURL = await QRCode.toDataURL(qrData, {
        width: 200,
        margin: 1,
      });
      setQrCodeDataURL(qrCodeURL);
    } catch (error) {
      console.error("Error generating QR code:", error);
      alert("Failed to generate QR code. Please try again.");
    }
  };

  const onSubmit = async (data: InvoiceData) => {
    // Validate QR code is generated for simplified invoices (B2C)
    if (data.invoiceType === "simplified" && !qrCodeDataURL) {
      alert(
        "⚠️ QR Code is mandatory for Simplified Tax Invoices (B2C)!\n\n" +
          "Please click the 'Generate QR Code' button before saving the invoice.\n\n" +
          "This is required for ZATCA Phase 1 compliance (Article 53, VAT Implementing Regulations)."
      );
      return;
    }

    setIsSaving(true);
    try {
      // Remove invoiceNumber from data - let backend auto-generate it
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { invoiceNumber, ...dataWithoutInvoiceNumber } = data;

      const invoiceData = {
        ...dataWithoutInvoiceNumber,
        qrCodeData: qrCodeDataURL,
      };

      const response = await fetch("/api/invoices", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(invoiceData),
      });

      if (response.ok) {
        const result = await response.json();
        console.log("Invoice created:", result);

        // Reset the form to default values
        form.reset({
          customer: "",
          invoiceNumber: "",
          date: new Date().toISOString().split("T")[0],
          dueDate: new Date().toISOString().split("T")[0],
          invoiceType: "simplified",
          rowEntries: [
            { description: "", account: "", quantity: 1, price: 0, taxRate: "" as any },
          ],
          pricesExcludeTax: true,
          discountTotal: 0,
        });
        
        // Reset QR code
        setQrCodeDataURL(null);

        alert("Invoice saved successfully!");
        // Optionally navigate to invoices list
        // router.push("/invoices");
      } else {
        const error = await response.json();
        console.error("Error saving invoice:", error);
        alert("Failed to save invoice. Please try again.");
      }
    } catch (error) {
      console.error("Error submitting invoice:", error);
      alert("An error occurred. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Invoice</h1>
        {/* Header with Logo Upload */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
          <div className=" order-2 lg:order-1">
            <div className="grid grid-cols-1 gap-6 mb-8">
              <FormField
                control={form.control}
                name="customer"
                rules={{ required: "Customer is required" }}
                render={({ field, fieldState }) => (
                  <FormItem>
                    <FormLabel>Customer*</FormLabel>
                    <Combobox
                      {...field}
                      placeholder={isLoading ? "Loading customers..." : "Select customer"}
                      options={customers.map((customer) => ({
                        label: customer.name,
                        value: customer.id,
                      }))}
                      handleCreate={() => {
                        setOpenCustomerModal(true);
                      }}
                    />
                    {fieldState.error && (
                      <p className="text-sm text-red-500">{fieldState.error.message}</p>
                    )}
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="invoiceType"
                rules={{ required: "Invoice type is required" }}
                render={({ field, fieldState }) => (
                  <FormItem>
                    <FormLabel>Invoice Type*</FormLabel>
                    <Combobox
                      {...field}
                      placeholder="Select invoice type"
                      showCreateButton={false}
                      isSearchEnabled={false}
                      options={[
                        {
                          label: "Standard Tax Invoice (B2B/B2G)",
                          value: "standard",
                        },
                        {
                          label: "Simplified Tax Invoice (B2C)",
                          value: "simplified",
                        },
                      ]}
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      {invoiceType === "standard"
                        ? "For VAT-registered customers (B2B/B2G) - QR code optional"
                        : "For non-VAT-registered customers (B2C) - QR code mandatory"}
                    </p>
                    {fieldState.error && (
                      <p className="text-sm text-red-500">{fieldState.error.message}</p>
                    )}
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="invoiceNumber"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Invoice number</FormLabel>
                    <Input
                      {...field}
                      placeholder="Auto-generated (e.g., INV-1)"
                      disabled
                      className="bg-gray-50 cursor-not-allowed"
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      Invoice number will be automatically generated
                    </p>
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="date"
                rules={{ required: "Invoice date is required" }}
                render={({ field, fieldState }) => (
                  <FormItem>
                    <FormLabel>Date*</FormLabel>
                    <Input type="date" {...field} />
                    {fieldState.error && (
                      <p className="text-sm text-red-500">{fieldState.error.message}</p>
                    )}
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="dueDate"
                rules={{ required: "Due date is required" }}
                render={({ field, fieldState }) => (
                  <FormItem>
                    <FormLabel>Due date*</FormLabel>
                    <Input type="date" {...field} />
                    {fieldState.error && (
                      <p className="text-sm text-red-500">{fieldState.error.message}</p>
                    )}
                  </FormItem>
                )}
              />
            </div>
          </div>

          {/* Company Details Section */}
          <div
            className="flex flex-col order-1 lg:order-2 gap-2 text-center lg:text-right lg:justify-self-end justify-self-center cursor-pointer hover:opacity-80 transition-opacity"
            onClick={() => router.push("/company-info")}
            title="Click to edit company information"
          >
            <Label className="justify-center">Company details</Label>
            <div className="border border-gray-200 shadow-xs flex items-center justify-center w-60 h-60 relative rounded-lg overflow-hidden bg-gray-50">
              {user.companyLogo?.url ? (
                <Image
                  src={user.companyLogo.url}
                  alt={user.companyLogo.alt || "Company logo"}
                  fill
                  sizes="(max-width: 768px) 100px, 150px"
                  className="object-contain"
                />
              ) : (
                <div className="flex flex-col items-center gap-2 text-gray-400">
                  <Image
                    src="/logo.png"
                    alt="logo"
                    width={100}
                    height={100}
                    className="object-contain"
                  />
                  <p className="text-xs">Click to add logo</p>
                </div>
              )}
            </div>

            <div className="text-sm">
              <p className="font-semibold text-gray-900">
                {user.companyName || "Company Name"}
              </p>
              <p className="text-gray-600">{user.address?.country || "Country"}</p>
              <p className="text-gray-600">
                Tax registration number: {user.vatNumber || "—"}
              </p>
              {user.phone && <p className="text-gray-600">{user.phone}</p>}
            </div>
            <p className="text-xs text-blue-600 mt-1">Click to edit company info</p>
          </div>
        </div>

        {/* Entries Section */}
        <div className="space-y-4">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-gray-900">Entries</h2>
            <div className="text-sm text-gray-600">
              Prices are
              <button
                type="button"
                className="text-blue-600 hover:underline ml-1 cursor-pointer font-medium"
                onClick={() => form.setValue("pricesExcludeTax", !pricesExcludeTax)}
              >
                {pricesExcludeTax ? "exc. tax" : "inc. tax"}
              </button>
            </div>
          </div>

          {/* Entries Table */}
          <div className="overflow-x-auto">
            <table className="w-full text-sm bg-gray-50 rounded-xl">
              <thead className="border-b border-gray-200">
                <tr className="*:py-2 *:px-3 *:font-semibold text-gray-700">
                  <th className="text-left">Description*</th>
                  <th className="text-left">Account*</th>
                  <th className="text-center w-24">Qty*</th>
                  <th className="text-center w-34">Price*</th>
                  <th className="text-center w-34">VAT*</th>
                  <th className="text-right w-34">Total</th>
                  <th className="text-right w-10">
                    <EllipsisVertical size={12} />
                  </th>
                </tr>
              </thead>
              <tbody>
                {fields.map((field, index) => (
                  <tr
                    key={field.id}
                    className="border-b *:px-3 *:py-3 *:align-top border-gray-100"
                  >
                    <td>
                      <FormField
                        control={form.control}
                        name={`rowEntries.${index}.description`}
                        rules={{ required: "Description is required" }}
                        render={({ field, fieldState }) => (
                          <>
                            <Input
                              placeholder="Required"
                              {...field}
                              className="text-sm"
                            />
                            {fieldState.error && (
                              <p className="text-xs text-red-500 mt-1">
                                {fieldState.error.message}
                              </p>
                            )}
                          </>
                        )}
                      />
                    </td>
                    <td>
                      <FormField
                        control={form.control}
                        name={`rowEntries.${index}.account`}
                        rules={{ required: "Account is required" }}
                        render={({ field, fieldState }) => (
                          <>
                            <Combobox
                              {...field}
                              handleCreate={() => {
                                setOpenAccountModal(true);
                              }}
                              placeholder="select"
                              options={accounts.map((account) => ({
                                label: account.name,
                                value: account.name,
                              }))}
                            />
                            {fieldState.error && (
                              <p className="text-xs text-red-500 mt-1">
                                {fieldState.error.message}
                              </p>
                            )}
                          </>
                        )}
                      />
                    </td>
                    <td className="text-center">
                      <FormField
                        control={form.control}
                        name={`rowEntries.${index}.quantity`}
                        rules={{
                          required: "Quantity is required",
                          min: { value: 1, message: "Quantity must be at least 1" },
                        }}
                        render={({ field, fieldState }) => (
                          <>
                            <Input
                              type="number"
                              min="1"
                              {...field}
                              onChange={(e) => field.onChange(Number(e.target.value))}
                              className="text-sm text-center"
                            />
                            {fieldState.error && (
                              <p className="text-xs text-red-500 mt-1">
                                {fieldState.error.message}
                              </p>
                            )}
                          </>
                        )}
                      />
                    </td>
                    <td className="text-center">
                      <FormField
                        control={form.control}
                        name={`rowEntries.${index}.price`}
                        rules={{
                          required: "Price is required",
                          min: { value: 0, message: "Price must be 0 or greater" },
                        }}
                        render={({ field, fieldState }) => (
                          <>
                            <Input
                              type="number"
                              value={field.value || ""}
                              onChange={(e) => {
                                const value = e.target.value;
                                // Remove leading zeros unless it's just "0"
                                const numValue = value === "" ? "" : Number(value);
                                field.onChange(numValue);
                              }}
                              onBlur={field.onBlur}
                              name={field.name}
                              className="text-sm text-center"
                              placeholder="0.00"
                            />
                            {fieldState.error && (
                              <p className="text-xs text-red-500 mt-1">
                                {fieldState.error.message}
                              </p>
                            )}
                          </>
                        )}
                      />
                    </td>
                    <td className="text-center">
                      <FormField
                        control={form.control}
                        name={`rowEntries.${index}.taxRate`}
                        rules={{ required: "VAT rate is required" }}
                        render={({ field, fieldState }) => (
                          <>
                            <Combobox
                              {...field}
                              placeholder="VAT Rate"
                              showCreateButton={false}
                              isSearchEnabled={false}
                              options={[
                                { label: "15% VAT", value: "15" },
                                { label: "10% VAT", value: "10" },
                                { label: "0% VAT", value: "0" },
                              ]}
                              onChange={(value) => field.onChange(Number(value))}
                              value={field.value?.toString() || ""}
                            />
                            {fieldState.error && (
                              <p className="text-xs text-red-500 mt-1">
                                {fieldState.error.message}
                              </p>
                            )}
                          </>
                        )}
                      />
                    </td>
                    <td className="text-right  font-medium text-gray-900">
                      <div className="flex items-center h-9 justify-end gap-2">
                        <span className="text-gray-500 text-xs">SAR</span>
                        <span>{calculateLineTotal(rowEntries[index]).toFixed(2)}</span>
                      </div>
                    </td>
                    <td
                      className={`text-right text-red-500 ${fields.length <= 1 ? "cursor-not-allowed opacity-50" : " cursor-pointer"}`}
                      onClick={fields.length > 1 ? () => remove(index) : undefined}
                    >
                      <div className="h-9 flex items-center justify-end">
                        <LucideTrash2 size={18} />
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Add/Clear Buttons */}
          <div className="flex gap-2 mt-4">
            <Button
              type="button"
              variant="outline"
              onClick={() =>
                append({
                  description: "",
                  account: "",
                  quantity: 1,
                  price: 0,
                  taxRate: "" as any,
                })
              }
              className="gap-2"
            >
              <Plus className="w-4 h-4" />
              Add line
            </Button>
          </div>
        </div>

        {/* Summary Section with QR Code */}
        <div className="flex justify-between items-start mt-8">
          {/* QR Code Section - Bottom Left */}
          <div className="flex flex-col gap-4">
            {qrCodeDataURL ? (
              <>
                <div className="border border-gray-200 rounded-lg p-4 bg-white shadow-sm">
                  <Image
                    src={qrCodeDataURL}
                    alt="Invoice QR Code"
                    width={200}
                    height={200}
                    className="rounded"
                  />
                  <p className="text-xs text-gray-500 text-center mt-2">
                    ZATCA E-Invoice QR Code
                  </p>
                </div>
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleGenerateQRCode}
                  className="w-full"
                >
                  Regenerate QR Code
                </Button>
              </>
            ) : (
              <div className="flex flex-col gap-4">
                <div
                  className={`border rounded-lg p-4 w-[232px] ${
                    invoiceType === "simplified"
                      ? "border-orange-300 bg-orange-50"
                      : "border-gray-200 bg-gray-50"
                  }`}
                >
                  <div className="flex flex-col items-center justify-center h-[200px] text-gray-400">
                    <p className="text-xs text-center">
                      {invoiceType === "simplified" ? (
                        <>
                          <span className="text-orange-600 font-semibold block mb-2">
                            ⚠️ QR Code Required
                          </span>
                          <span className="text-gray-600">
                            Mandatory for Simplified
                            <br />
                            Tax Invoices (B2C)
                          </span>
                        </>
                      ) : (
                        <>
                          Click the button below
                          <br />
                          to generate QR code
                          <br />
                          <span className="text-gray-500">(Optional for B2B)</span>
                        </>
                      )}
                    </p>
                  </div>
                </div>
                <Button
                  type="button"
                  variant={invoiceType === "simplified" ? "default" : "outline"}
                  onClick={handleGenerateQRCode}
                  className="w-full"
                >
                  Generate QR Code{invoiceType === "simplified" ? " (Required)" : " (Optional)"}
                </Button>
              </div>
            )}
          </div>

          {/* Summary - Right Side */}
          <div className="w-full max-w-xs space-y-2">
            <div className="flex justify-between text-sm py-2 border-b border-gray-200">
              <span className="text-gray-600">
                Subtotal {pricesExcludeTax ? "(excl. VAT)" : "(incl. VAT)"}
              </span>
              <span className="font-medium">SAR {subtotal.toFixed(2)}</span>
            </div>
            <div className="flex justify-between text-sm py-2 border-b border-gray-200">
              <span className="text-gray-600">VAT Amount</span>
              <span className="font-medium">SAR {tax.toFixed(2)}</span>
            </div>
            <div className="flex justify-between font-semibold py-3">
              <span>Total (incl. VAT)</span>
              <span>SAR {total.toFixed(2)}</span>
            </div>
          </div>
        </div>

        {/* Submit Button */}
        <div className="flex gap-3 mt-8">
          <Button type="submit" disabled={isSaving}>
            {isSaving ? "Saving..." : "Save Invoice"}
          </Button>
          <Button
            type="button"
            variant="outline"
            onClick={() => router.push("/invoices")}
            disabled={isSaving}
          >
            Cancel
          </Button>
        </div>
      </form>
      <CustomerCreateModal
        open={openCustomerModal}
        setOpen={setOpenCustomerModal}
        onCustomerCreated={fetchCustomers}
      />
      <AccountCreateModal
        open={openAccountModal}
        setOpen={setOpenAccountModal}
        onAccountCreated={fetchAccounts}
      />
    </Form>
  );
}
